# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  #### Certificates ####
  desc "Install certificates and provisioning profiles"
  lane :certificates do |options|
    readonly = (options[:refresh_certificates] ? false : true)

    match(
      type: "appstore",
      readonly: readonly
    )
  end

  #### Testing ####
  desc "Run all tests"
  lane :tests do
    run_tests(scheme: "WWDCScholarsTests")
  end

  #### Build & Release ####
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    certificates(
      refresh_certificates: options[:refresh_certificates]
    )

    increment_build_number

    gym(
      scheme: "WWDCScholars",
      configuration: "Beta",
      clean: true,
      include_symbols: true,
      export_method: "app-store",
      verbose: true
    )

    testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
