# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    # sh('git init')
    sh('git config --global user.name "WWDCScholars-bot"')
    sh('git config --global user.email "wwdcscholars@logicbit.nl"')
    # sh('git remote set-url origin https://$GH_TOKEN@github.com/WWDCScholars/WWDCScholars-iOS.git')
    # ensure_git_status_clean
    increment_build_number

  end

  desc "Runs all the tests"
  lane :test do
    gym(scheme: "WWDCScholars", silent: true)
    # scan
  end

  lane :screenshot do
    snapshot(skip_open_summary: true, devices: ["iPhone 6"])
  end

  desc "Deploy a new bleeding-edge version to Crashlytics beta"
  lane :crashlytics do
    match(git_url: "git@github.com:WWDCScholars/certificates.git", type: "appstore", readonly: true)
    gym(scheme: "WWDCScholars", silent: true)
    scan
    snapshot(skip_open_summary: true, devices: ["iPhone 6"])
    # crashlytics
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight do
    match(git_url: "git@github.com:WWDCScholars/certificates.git", type: "appstore", readonly: true)
    gym(scheme: "WWDCScholars", silent: true)
    scan
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    match(git_url: "git@github.com:WWDCScholars/certificates.git", type: "appstore", readonly: true)
    snapshot
    gym(scheme: "WWDCScholars", silent: true) # Build your app - more options available
    scan
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # sh('rm -i id_rsa')
    # This block is called, only if the executed lane was successful
    version     = get_version_number(xcodeproj: "WWDCScholars.xcodeproj")
    build       = get_build_number(xcodeproj: "WWDCScholars.xcodeproj")

    slack(
      message: "Successfully deployed version *#{version}* (#{build})! :tim: :tada:"
    )

    sh('git add --all')
    # git_commit(
    #   message: "Version #{version}, Build #{build}\n[ci skip]"
    # )
    sh("git commit -m \"Version #{version}, Build #{build}\n[ci skip]\"")
    # git_commit # Commit snapshot files and stuff

    sh('git pull --rebase')

    push_to_git_remote(remote: "git@github.com:WWDCScholars/WWDCScholars-iOS.git", remote_branch: ENV["TRAVIS_BRANCH"], force: true)

  end

  error do |lane, exception|
    slack(
      message: "Build failed! :sad-steve: " + exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
